### ISSUE TITLE
provide an OpenShift template

### ISSUE THREAD

**Issue by goern** [RHsyseng/docker-rhel-sonarqube#1]

**Comment by goern** [comment]
pls chk https://github.com/RHsyseng/docker-rhel-sonarqube/tree/feature/merging-with-openshift-demos

**Comment by tchughesiv** [comment]
some good stuff here... i've got some additional required mods i've added to the template since we're using a rhel-based image that doesn't exist on either redhat's registry or docker's.  Also, I'll commit the dockerfile mods but ill be re-basing it back to rhel7 since the jboss image is centos7 based and installs has other things i doubt sonarsource would want.

**Comment by tchughesiv** [comment]
ok, i think we've got something.  had to use a dockerfile buildconfig because the sonarqube image doesn't exist in any public registry... and i can't upload the rhel image to docker hub.  seems to work well though... just hve to ensure that your build user has rights to push to the internal registry and a secret is setup.

also, the first yum clean all in the docker file is there just to trigger the container's repolist at build time... i've noticed sometimes it won't trigger correctly during builds and it will wind up using all of the host's repos to install with instead of the one we dictate.

let me know if i can close this.
